version: "3.4"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: unless-stopped
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - smPostNetwork
      
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    restart: unless-stopped
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    depends_on:
      - zookeeper
    networks:
      - smPostNetwork
      
  mongo:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]    # add replica set to be able to use transactions
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
    networks:
      - smPostNetwork
      
  mongo-init:     # Initialize Replica Set for MongoDB (to be able to use transactions)
    image: mongo:7
    depends_on:
      - mongo
    networks:
      - smPostNetwork
    command: >
      bash -c "
        sleep 5 &&
        mongosh --host mongo:27017 --eval '
          try {
            rs.status();
          } catch (e) {
            rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"mongo:27017\" }]
            });
          }
        '
      "
    
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    ports:
      - "1401:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd!"
      MSSQL_PID: "Express"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 30

    volumes:
      - "sqlserver_data:/var/opt/mssql"
    networks:
      - smPostNetwork
    
  command-api:
    build:
      context: .
      dockerfile: Post.Cmd/Post.Cmd.Api/Dockerfile
    environment:
      - KAFKA_TOPIC=SocialMediaPostEvents
    ports:
      - "5010:80"
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_started
      mongo:
        condition: service_started
      sql-server:
        condition: service_healthy
    networks:
      - smPostNetwork

  query-api:
    build:
      context: .
      dockerfile: Post.Query/Post.Query.Api/Dockerfile
    environment:
      - KAFKA_TOPIC=SocialMediaPostEvents
    ports:
      - "5011:80"
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_started
      mongo:
        condition: service_started
      sql-server:
        condition: service_healthy
    networks:
      - smPostNetwork

  ocelot-gateway:
    build:
      context: .
      dockerfile: Gateway.Ocelot/Dockerfile
    ports:
      - "7006:80"
    restart: unless-stopped
    depends_on:
      - command-api
      - query-api
    networks:
      - smPostNetwork

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
  sqlserver_data:
    driver: local
    
networks:
  smPostNetwork:
    driver: bridge
